# Generated by Django 4.1.4 on 2022-12-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=256)),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'directors',
            },
        ),
        migrations.CreateModel(
            name='DirectorGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=256)),
                ('prob', models.FloatField()),
            ],
            options={
                'db_table': 'directors_genres',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=256)),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='actors.actor')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
    ]
