# Generated by Django 4.1.4 on 2022-12-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='directorgenre',
            name='director_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='actors.director'),
        ),
    ]
