# Generated by Django 4.1.4 on 2022-12-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directorgenre',
            old_name='director_id',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='actor_id',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
