# Generated by Django 4.1.4 on 2022-12-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('rank', models.FloatField()),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=256)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movie')),
            ],
            options={
                'db_table': 'movies_genres',
            },
        ),
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='actors.director')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movie')),
            ],
            options={
                'db_table': 'movies_directors',
            },
        ),
    ]
