# Generated by Django 4.1.4 on 2022-12-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_movie_id_moviedirector_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rank',
            field=models.FloatField(null=True),
        ),
    ]
