# Generated by Django 4.1.4 on 2022-12-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedirector',
            old_name='director_id',
            new_name='director',
        ),
    ]
